/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: string;
                    GreenhouseId?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfAlertResponse"];
                        "application/json": components["schemas"]["PagedResponseOfAlertResponse"];
                        "text/json": components["schemas"]["PagedResponseOfAlertResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlertResponse"];
                        "application/json": components["schemas"]["AlertResponse"];
                        "text/json": components["schemas"]["AlertResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AlertResponse"];
                        "application/json": components["schemas"]["AlertResponse"];
                        "text/json": components["schemas"]["AlertResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RefreshResponse"];
                        "application/json": components["schemas"]["RefreshResponse"];
                        "text/json": components["schemas"]["RefreshResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MeResponse"];
                        "application/json": components["schemas"]["MeResponse"];
                        "text/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardSummaryResponse"];
                        "application/json": components["schemas"]["DashboardSummaryResponse"];
                        "text/json": components["schemas"]["DashboardSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/greenhouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseDetailResponse"];
                        "application/json": components["schemas"]["GreenhouseDetailResponse"];
                        "text/json": components["schemas"]["GreenhouseDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/greenhouse/{greenhouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    greenhouseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceResponse"][];
                        "application/json": components["schemas"]["DeviceResponse"][];
                        "text/json": components["schemas"]["DeviceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    From?: string;
                    To?: string;
                    Limit?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceReadingsResponse"];
                        "application/json": components["schemas"]["DeviceReadingsResponse"];
                        "text/json": components["schemas"]["DeviceReadingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceResponse"];
                        "application/json": components["schemas"]["DeviceResponse"];
                        "text/json": components["schemas"]["DeviceResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRequest"];
                    "text/json": components["schemas"]["DeviceRequest"];
                    "application/*+json": components["schemas"]["DeviceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceResponse"];
                        "application/json": components["schemas"]["DeviceResponse"];
                        "text/json": components["schemas"]["DeviceResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceRequest"];
                    "text/json": components["schemas"]["DeviceRequest"];
                    "application/*+json": components["schemas"]["DeviceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceWithTokenResponse"];
                        "application/json": components["schemas"]["DeviceWithTokenResponse"];
                        "text/json": components["schemas"]["DeviceWithTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceWithTokenResponse"];
                        "application/json": components["schemas"]["DeviceWithTokenResponse"];
                        "text/json": components["schemas"]["DeviceWithTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/greenhouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseResponse"][];
                        "application/json": components["schemas"]["GreenhouseResponse"][];
                        "text/json": components["schemas"]["GreenhouseResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GreenhouseRequest"];
                    "text/json": components["schemas"]["GreenhouseRequest"];
                    "application/*+json": components["schemas"]["GreenhouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseResponse"];
                        "application/json": components["schemas"]["GreenhouseResponse"];
                        "text/json": components["schemas"]["GreenhouseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/greenhouses/{id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Metric?: string;
                    From?: string;
                    To?: string;
                    Bucket?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseReadingsResponse"];
                        "application/json": components["schemas"]["GreenhouseReadingsResponse"];
                        "text/json": components["schemas"]["GreenhouseReadingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/greenhouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseResponse"];
                        "application/json": components["schemas"]["GreenhouseResponse"];
                        "text/json": components["schemas"]["GreenhouseResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GreenhouseRequest"];
                    "text/json": components["schemas"]["GreenhouseRequest"];
                    "application/*+json": components["schemas"]["GreenhouseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GreenhouseResponse"];
                        "application/json": components["schemas"]["GreenhouseResponse"];
                        "text/json": components["schemas"]["GreenhouseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestRequest"];
                    "text/json": components["schemas"]["IngestRequest"];
                    "application/*+json": components["schemas"]["IngestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestBatchRequest"];
                    "text/json": components["schemas"]["IngestBatchRequest"];
                    "application/*+json": components["schemas"]["IngestBatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thresholds/greenhouse/{greenhouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    greenhouseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ThresholdResponse"][];
                        "application/json": components["schemas"]["ThresholdResponse"][];
                        "text/json": components["schemas"]["ThresholdResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thresholds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ThresholdResponse"];
                        "application/json": components["schemas"]["ThresholdResponse"];
                        "text/json": components["schemas"]["ThresholdResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThresholdRequest"];
                    "text/json": components["schemas"]["ThresholdRequest"];
                    "application/*+json": components["schemas"]["ThresholdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ThresholdResponse"];
                        "application/json": components["schemas"]["ThresholdResponse"];
                        "text/json": components["schemas"]["ThresholdResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThresholdRequest"];
                    "text/json": components["schemas"]["ThresholdRequest"];
                    "application/*+json": components["schemas"]["ThresholdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ThresholdResponse"];
                        "application/json": components["schemas"]["ThresholdResponse"];
                        "text/json": components["schemas"]["ThresholdResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            greenhouseId: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: uuid */
            thresholdId: string;
            metric: components["schemas"]["MetricType"];
            /** Format: double */
            triggeredValue: number | string;
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            /** Format: date-time */
            triggeredAt: string;
            /** Format: date-time */
            resolvedAt: null | string;
        };
        AlertSeverity: number;
        AlertStatus: number;
        DashboardSummaryResponse: {
            greenhouses: components["schemas"]["GreenhouseSummary"][];
        };
        DeviceReadingsResponse: {
            /** Format: uuid */
            deviceId: string;
            metric: string;
            readings: components["schemas"]["ReadingPoint"][];
        };
        DeviceRequest: {
            name: string;
            /** Format: uuid */
            greenhouseId: string;
            metric: components["schemas"]["MetricType"];
        };
        DeviceResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            greenhouseId: string;
            metric: components["schemas"]["MetricType"];
            status: string;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceWithTokenResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            greenhouseId: string;
            metric: components["schemas"]["MetricType"];
            token: string;
        };
        GreenhouseDetailResponse: {
            /** Format: uuid */
            greenhouseId: string;
            name: string;
            location: null | string;
            metrics: components["schemas"]["MetricSummary"][];
            activeAlerts: components["schemas"]["AlertResponse"][];
        };
        GreenhouseReadingsResponse: {
            /** Format: uuid */
            greenhouseId: string;
            metric: string;
            bucket: string;
            points: components["schemas"]["RollupPoint"][];
        };
        GreenhouseRequest: {
            name: string;
            location: string;
        };
        GreenhouseResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            location: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        GreenhouseSummary: {
            /** Format: uuid */
            greenhouseId: string;
            name: string;
            /** Format: int32 */
            deviceCount: number | string;
            /** Format: int32 */
            activeAlerts: number | string;
            metrics: components["schemas"]["MetricCurrent"][];
        };
        IngestBatchRequest: {
            readings: components["schemas"]["IngestRequest"][];
        };
        IngestRequest: {
            metric: string;
            /** Format: double */
            value: number | string;
            /** Format: date-time */
            recordedAt: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** Format: int32 */
            expiresIn: number | string;
            user: components["schemas"]["UserInfo"];
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            role: string;
            /** Format: uuid */
            organizationId: string;
        };
        MetricCurrent: {
            metric: components["schemas"]["MetricType"];
            /** Format: double */
            current: number | string;
        };
        MetricSummary: {
            metric: components["schemas"]["MetricType"];
            /** Format: double */
            current: number | string;
            /** Format: double */
            min24h: number | string;
            /** Format: double */
            max24h: number | string;
            /** Format: double */
            avg24h: number | string;
        };
        MetricType: number;
        PagedResponseOfAlertResponse: {
            items: components["schemas"]["AlertResponse"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        ReadingPoint: {
            /** Format: date-time */
            recordedAt: string;
            /** Format: double */
            value: number | string;
        };
        RefreshResponse: {
            accessToken: string;
            /** Format: int32 */
            expiresIn: number | string;
        };
        RegisterRequest: {
            organizationName: string;
            email: string;
            password: string;
        };
        RollupPoint: {
            /** Format: date-time */
            periodStart: string;
            /** Format: double */
            min: number | string;
            /** Format: double */
            max: number | string;
            /** Format: double */
            avg: number | string;
            /** Format: int32 */
            count: number | string;
        };
        ThresholdRequest: {
            /** Format: uuid */
            greenhouseId: string;
            metric: components["schemas"]["MetricType"];
            /** Format: double */
            minValue: null | number | string;
            /** Format: double */
            maxValue: null | number | string;
            isEnabled: boolean;
        };
        ThresholdResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            greenhouseId: string;
            metric: components["schemas"]["MetricType"];
            /** Format: double */
            minValue: null | number | string;
            /** Format: double */
            maxValue: null | number | string;
            isEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UserInfo: {
            /** Format: uuid */
            id: string;
            email: string;
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
